#!/usr/bin/env bash
# the script will change address ip localhost to 127.0.0.2 and facebook.com to 8.8.8.8
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts